name: Node.js CI

on: 
  push:
    # executar no branch
    branches: [main]
  pull_request: 
    # executar quando o pull request for no branch
    branches: [main]
#   schedule:
#     - cron: '31 7 * * 3'

jobs:
  pre-build:
    name: Job de análise, antes do build
    
    # rodar em um docker ubuntu-latest
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    # configurações
    strategy:
      fail-fast: false
      matrix:
        language: [ 'TypeScript' ]
        minha_variavel: ['teste']
        nome_projeto: ['base para projetos']

    # execução:
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          source-root: src
          
      # Autobuild 
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      # executa a análise
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  build:
    # rodar em um docker ubuntu-latest
    runs-on: ubuntu-latest

    # execução:
    steps:
      # clona o repositório
      - name: Checkout repo
        uses: actions/checkout@v3
      
      # instala o node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      # instala os pacotes
      - run: npm ci
      
      # se tiver build, então builda
      - run: npm run build --if-present
      
      # executa os testes
      - run: npm test
